<h1 style= "text-align:center"> Metodos LU </h1>

Condiciones de Algoritmos:

- Matrices para los 3 programas [10x10], [100x100], [1000x1000] y [10.000x10.000] 
- Matrices simetricas y diagonalmente dominantes
- Identificar el costo computacional

#### Librerias Necesarias:

<p> Para instalar cualquier libreria utilizar </p>
<p style="font-weight:normal; font-family: 'Inconsolata', monospace;">
import Pkg;
<br>
Pkg.add("NombreLibreria")
</p>


#### Nombre de Librerias:

- IJulia
- Gadfly 


In [8]:
#Librerias
using LinearAlgebra

#Generar Matrices Aleatorias
A = randn(10,10)
B = randn(100,100)
C = randn(1000,1000)
D = randn(10000,10000)

10000×10000 Array{Float64,2}:
 -0.44356     0.701905    0.501776   …   0.803149   0.355032   -0.583181 
 -1.31483    -1.0542      1.28043       -1.30555    0.752317   -1.06492  
  0.399201    1.15721    -0.063666      -0.210079  -0.333315    0.599    
 -0.937589    0.34882     1.53433        0.83183    0.680287   -0.132488 
  1.17328    -0.59839    -0.642663      -0.770884   1.30257     0.549424 
  0.81546     0.317818   -1.42789    …  -0.882604  -1.19187    -0.229157 
  0.790335    0.355464    0.248297      -1.70675    1.02852     1.51355  
  0.297595    0.99544    -0.304627       1.3477    -1.1579     -0.0848831
  0.0238982  -0.836874    0.0842957     -0.533192   0.595506   -0.49988  
  0.442928   -0.115027    1.3276        -0.903535  -0.217549   -1.05409  
 -0.0519491   0.206889   -0.46593    …   0.880219  -0.926786    0.23407  
 -1.3275      2.26341    -1.12632       -1.20063   -0.555728    1.36279  
 -1.84514     0.179414   -0.402148      -1.17001   -0.327597    0.162097 
  ⋮     

# Metodo LU

Existe un metodo predeterminado en una libreria de Julia, tomada de ejemplo de:

http://rosettacode.org/wiki/LU_decomposition

In [11]:
L,U,p = lu(A)
#Costo Computacional
@time lu(A);

  0.000391 seconds (7 allocations: 1.219 KiB)


### Implementacion Metodo LU - Doolitle

Implementacion del Metodo de Factorizacion LU - Doolitle, se hace la implementacion mediante una funcion para la reutilizacion del codigo.

<strong>Nota</strong>
Agregar la seccion de impresion de resultados si se desea visualizar las matrices L y U resultantes.

In [27]:
function luDoolitle(A)
    L = zeros(size(A));
    U = zeros(size(A));
    n=size(A)
    filas = n[1]
    columnas = n[2];

    for j=1:columnas
      for i=1:filas

        if i<=j
          U[i,j] = A[i,j];
          for k=1:i-1
            U[i,j] = U[i,j] - L[i,k]*U[k,j];
          end
        end    

        if j<=i
          L[i,j] = A[i,j];
          for k=1:j-1
            L[i,j] = L[i,j] - L[i,k]*U[k,j];
          end
          L[i,j] = L[i,j]/U[j,j];
        end
      end
    end
    #Impresion de las Matrices Resultantes
    ##Agregar codigo impresion##
end

##Codigo Impresion
"""
    println("\n\tResultados\n\nMatriz L : \n");
    println(L);
    println("\nMatriz U : \n");
    println(U);
"""

"    println(\"\n\tResultados\n\nMatriz L : \n\");\n    println(L);\n    println(\"\nMatriz U : \n\");\n    println(U);\n"

In [11]:
#Costo Computacional
println("Costo Computacional - Algoritmo Implementado")
@time luDoolitle(A)
println("Costo Computacional - Funcion de Libreria")
@time lu(A)


Tiempo de Ejecucion - Algoritmo Implementado
  0.000010 seconds (6 allocations: 1.906 KiB)
Tiempo de Ejecucion - Funcion de Libreria
  0.000346 seconds (7 allocations: 1.219 KiB)


LU{Float64,Array{Float64,2}}
L factor:
10×10 Array{Float64,2}:
  1.0         0.0         0.0        …   0.0        0.0        0.0
  0.49653     1.0         0.0            0.0        0.0        0.0
  0.356576    0.741092    1.0            0.0        0.0        0.0
 -0.0515437   0.972423   -0.253232       0.0        0.0        0.0
 -0.0232394   0.224695   -0.673696       0.0        0.0        0.0
 -0.271241    0.441704   -0.542356   …   0.0        0.0        0.0
 -0.0816821  -0.278193    0.139323       0.0        0.0        0.0
  0.348466   -0.985847   -0.255123       1.0        0.0        0.0
 -0.250669    0.478609   -0.0433264     -0.762326   1.0        0.0
 -0.489069    0.0653053  -0.150922      -0.584876  -0.0957765  1.0
U factor:
10×10 Array{Float64,2}:
 2.22654   0.509611  -1.75119    0.53508  …  -0.541183   1.37632    0.779757
 0.0      -0.838817   0.564152   0.81594     -0.378804   0.312368  -1.05287 
 0.0       0.0        2.07449   -1.40539     -0.891554  -1.02174    0.629453
 0

In [12]:
#Tiempo de Ejecucion 
println("#Costo Computacional - Algoritmo Implementado")
@time luDoolitle(B)
println("#Costo Computacional - Funcion de Libreria")
@time lu(B)

Tiempo de Ejecucion - Algoritmo Implementado
  0.000877 seconds (8 allocations: 156.563 KiB)
Tiempo de Ejecucion - Funcion de Libreria
  0.006405 seconds (8 allocations: 79.266 KiB)


LU{Float64,Array{Float64,2}}
L factor:
100×100 Array{Float64,2}:
  1.0         0.0         …  0.0        0.0        0.0       0.0
  0.443493    1.0            0.0        0.0        0.0       0.0
 -0.0815106  -0.517996       0.0        0.0        0.0       0.0
 -0.12234    -0.0760449      0.0        0.0        0.0       0.0
 -0.77348    -0.427135       0.0        0.0        0.0       0.0
  0.348795    0.422177    …  0.0        0.0        0.0       0.0
  0.358435   -0.114731       0.0        0.0        0.0       0.0
 -0.074621   -0.954082       0.0        0.0        0.0       0.0
  0.261908    0.74492        0.0        0.0        0.0       0.0
 -0.093684   -0.414347       0.0        0.0        0.0       0.0
 -0.5396     -0.0131085   …  0.0        0.0        0.0       0.0
  0.627407    0.284945       0.0        0.0        0.0       0.0
  0.221783   -0.11465        0.0        0.0        0.0       0.0
  ⋮                       ⋱                                     
 -0.232627   -0.231045   

In [13]:
#Costo Computacional
println("Costo Computacional - Algoritmo Implementado")
@time luDoolitle(C)
println("Costo Computacional - Funcion de Libreria")
@time lu(C)

Tiempo de Ejecucion - Algoritmo Implementado
  1.425529 seconds (8 allocations: 15.259 MiB)
Tiempo de Ejecucion - Funcion de Libreria
  0.053387 seconds (8 allocations: 7.637 MiB)


LU{Float64,Array{Float64,2}}
L factor:
1000×1000 Array{Float64,2}:
  1.0         0.0          0.0         …   0.0        0.0       0.0      0.0
 -0.325778    1.0          0.0             0.0        0.0       0.0      0.0
  0.421068   -0.706578     1.0             0.0        0.0       0.0      0.0
 -0.110383    0.32829     -0.0198629       0.0        0.0       0.0      0.0
 -0.442719    0.504822    -0.488284        0.0        0.0       0.0      0.0
 -0.115609    0.139457     0.170396    …   0.0        0.0       0.0      0.0
  0.625057    0.224672    -0.207444        0.0        0.0       0.0      0.0
 -0.0364743  -0.228408    -0.00415776      0.0        0.0       0.0      0.0
 -0.234011    0.341278    -0.279691        0.0        0.0       0.0      0.0
 -0.122175   -0.167697     0.103969        0.0        0.0       0.0      0.0
  0.384466   -0.226705    -0.0824713   …   0.0        0.0       0.0      0.0
  0.159834    0.514912    -0.0526012       0.0        0.0       0.0      0.0
 -0.48529

In [ ]:
#Costo Computacional
println("Costo Computacional - Algoritmo Implementado")
@time luDoolitle(D)
println("Costo Computacional - Funcion de Libreria")
@time lu(D)

Algoritmo
http://esfm.egormaximenko.com/numerical_methods/prog_LU_factorization_es.pdf
http://esfm.egormaximenko.com/numerical_methods/LU_factorization_presentation_es.pdf
Ejemplo Libreria LU:

# Metodo LU Crout

Implementacion del Metodo de Factorizacion LU - Crout, se hace la implementacion mediante una funcion para la reutilizacion del codigo.

<strong>
Nota
</strong> 
Descomentar la seccion de impresion de resultados si se desea visualizar las matrices L y U resultantes.

In [28]:
function luCrout(A)
    L = zeros(size(A));
    u = zeros(size(A));
    nM=size(A);
    n = nM[1];
    m = nM[2];
    
    if n==m 
        for k=1:n
            u[k,k]=1; 
            suma=0;
            for p=1:k-1
                suma=suma+L[k,p]*u[p,k];
            end
            L[k,k]=A[k,k]-suma; 

            for i=k+1:n
                suma=0;
                for r=1:k-1
                    suma=suma+L[i,r]*u[r,k];
                end
                L[i,k]=A[i,k]-suma; 
            end
            for j=k+1:n
                suma=0;
                for s=1:k-1
                    suma=suma+L[k,s]*u[s,j];
                end
                u[k,j]=A[k,j]-suma/L[k,k]; 
            end
        end
        
    else
        println("\nLa matriz debe ser cuadrada para factorizar mediante LU Crout\n");
    end
end

##Codigo Impresion
"""
        println("Descomposicion Crout");
        println("\n Matriz L:\n")
        println(L)
        println("\n Matriz U:\n")
        println(u) 
"""

"        println(\"Descomposicion Crout\");\n        println(\"\n Matriz L:\n\")\n        println(L)\n        println(\"\n Matriz U:\n\")\n        println(u) \n"

In [29]:
#Costo Computacional 
println("Costo Computacional - Algoritmo Implementado")
@time luCrout(A)
println("Costo Computacional - Funcion de Libreria")
@time lu(A)

Tiempo de Ejecucion - Algoritmo Implementado
  0.077381 seconds (53.85 k allocations: 2.634 MiB)
Tiempo de Ejecucion - Funcion de Libreria
  0.000338 seconds (7 allocations: 1.219 KiB)


LU{Float64,Array{Float64,2}}
L factor:
10×10 Array{Float64,2}:
  1.0        0.0        0.0       …  0.0         0.0       0.0       0.0
  0.498361   1.0        0.0          0.0         0.0       0.0       0.0
 -0.621274  -0.20924    1.0          0.0         0.0       0.0       0.0
  0.556392   0.813669   0.215415     0.0         0.0       0.0       0.0
 -0.269703  -0.770947  -0.423806     0.0         0.0       0.0       0.0
  0.208165  -0.445069   0.618079  …  0.0         0.0       0.0       0.0
  0.198068  -0.170939   0.817989     1.0         0.0       0.0       0.0
 -0.500811  -0.182488   0.317421     0.0163752   1.0       0.0       0.0
  0.621214  -0.374722   0.665546     0.305194   -0.746156  1.0       0.0
  0.279159  -0.264935  -0.120677     0.374217   -0.666125  0.319299  1.0
U factor:
10×10 Array{Float64,2}:
 1.35464  0.038165   0.536904  -1.33188  …  -1.44208   -0.0401047   1.25026 
 0.0      1.7143    -0.316444  -1.21389      1.41465    1.06765    -0.24913 
 0.0      0.0      

In [30]:
#Costo Computacional 
println("Costo Computacional - Algoritmo Implementado")
@time luCrout(A)
println("Costo Computacional - Funcion de Libreria")
@time lu(A)

Tiempo de Ejecucion - Algoritmo Implementado
  0.000012 seconds (6 allocations: 1.906 KiB)
Tiempo de Ejecucion - Funcion de Libreria
  0.000246 seconds (7 allocations: 1.219 KiB)


LU{Float64,Array{Float64,2}}
L factor:
10×10 Array{Float64,2}:
  1.0        0.0        0.0       …  0.0         0.0       0.0       0.0
  0.498361   1.0        0.0          0.0         0.0       0.0       0.0
 -0.621274  -0.20924    1.0          0.0         0.0       0.0       0.0
  0.556392   0.813669   0.215415     0.0         0.0       0.0       0.0
 -0.269703  -0.770947  -0.423806     0.0         0.0       0.0       0.0
  0.208165  -0.445069   0.618079  …  0.0         0.0       0.0       0.0
  0.198068  -0.170939   0.817989     1.0         0.0       0.0       0.0
 -0.500811  -0.182488   0.317421     0.0163752   1.0       0.0       0.0
  0.621214  -0.374722   0.665546     0.305194   -0.746156  1.0       0.0
  0.279159  -0.264935  -0.120677     0.374217   -0.666125  0.319299  1.0
U factor:
10×10 Array{Float64,2}:
 1.35464  0.038165   0.536904  -1.33188  …  -1.44208   -0.0401047   1.25026 
 0.0      1.7143    -0.316444  -1.21389      1.41465    1.06765    -0.24913 
 0.0      0.0      

In [31]:
#Costo Computacional
println("Costo Computacional - Algoritmo Implementado")
@time luCrout(B)
println("Costo Computacional - Funcion de Libreria")
@time lu(B)

Tiempo de Ejecucion - Algoritmo Implementado
  0.000847 seconds (8 allocations: 156.563 KiB)
Tiempo de Ejecucion - Funcion de Libreria
  0.007006 seconds (8 allocations: 79.266 KiB)


LU{Float64,Array{Float64,2}}
L factor:
100×100 Array{Float64,2}:
  1.0         0.0         0.0        …   0.0        0.0       0.0
  0.553614    1.0         0.0            0.0        0.0       0.0
 -0.0298641  -0.519915    1.0            0.0        0.0       0.0
 -0.815413    0.751376    0.12508        0.0        0.0       0.0
  0.661543    0.01537     0.185152       0.0        0.0       0.0
  0.160602   -0.735242   -0.381766   …   0.0        0.0       0.0
  0.0307791   0.783407   -0.28775        0.0        0.0       0.0
  0.877754    0.264923   -0.47269        0.0        0.0       0.0
  0.209523    0.785998    0.0778987      0.0        0.0       0.0
 -0.663316    0.344518    0.134445       0.0        0.0       0.0
 -0.0710074  -0.110186    0.542551   …   0.0        0.0       0.0
  0.408645    0.314744    0.428686       0.0        0.0       0.0
 -0.7737      0.485503    0.510469       0.0        0.0       0.0
  ⋮                                  ⋱                           
  0.354514 

In [32]:
#Costo Computacional
println("Costo Computacional - Algoritmo Implementado")
@time luCrout(C)
println("Costo Computacional - Funcion de Libreria")
@time lu(C)

Tiempo de Ejecucion - Algoritmo Implementado
  1.381879 seconds (8 allocations: 15.259 MiB)
Tiempo de Ejecucion - Funcion de Libreria
  0.039819 seconds (8 allocations: 7.637 MiB)


LU{Float64,Array{Float64,2}}
L factor:
1000×1000 Array{Float64,2}:
  1.0         0.0         0.0        …   0.0        0.0        0.0
  0.108713    1.0         0.0            0.0        0.0        0.0
 -0.559846   -0.560647    1.0            0.0        0.0        0.0
  0.088832    0.636843   -0.396097       0.0        0.0        0.0
 -0.233314    0.0597784  -0.262203       0.0        0.0        0.0
  0.514831   -0.071823    0.4399     …   0.0        0.0        0.0
  0.419491    0.618725   -0.795188       0.0        0.0        0.0
  0.493557   -0.178329   -0.386859       0.0        0.0        0.0
 -0.0912327  -0.142706    0.103352       0.0        0.0        0.0
  0.549888    0.0392015  -0.556573       0.0        0.0        0.0
 -0.317196    0.471087   -0.171653   …   0.0        0.0        0.0
 -0.146378    0.0951256  -0.380374       0.0        0.0        0.0
 -0.324428    0.876275   -0.502335       0.0        0.0        0.0
  ⋮                                  ⋱                        

In [ ]:
#Costo Computacional
println("Costo Computacional - Algoritmo Implementado")
@time luCrout(D)
println("Costo Computacional - Funcion de Libreria")
@time lu(D)

### Explicacion General del metodo de Factorizacion

http://esfm.egormaximenko.com/numerical_analysis1.html#partcg